'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
const roles={seeker:['Job Seeker','seeker@jobhub.local'],fresher:['Student / Fresher','fresher@jobhub.local'],professional:['Working Professional','professional@jobhub.local'],recruiter:['Recruiter / Hiring Manager','recruiter@jobhub.local'],employer:['Company / Employer','employer@jobhub.local'],admin:['Admin / Platform Ops','admin@jobhub.local']};
export default function Login(){const router=useRouter();const [role,setRole]=useState('seeker');const [email,setEmail]=useState(roles.seeker[1]);const [password,setPassword]=useState('parrot421$');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('role');if(requested && roles[requested]){setRole(requested);setEmail(roles[requested][1])}},[]);
useEffect(()=>{setEmail(roles[role][1])},[role]);
async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`/api/v1/auth/demo-login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Login failed');localStorage.setItem('jobhub.accessToken',data.token);localStorage.setItem('jobhub.user',JSON.stringify(data.user));router.push('/portal')}catch(err){setError(err.message)}finally{setBusy(false)}}
return <main className="loginPage"><div className="loginCard"><section className="loginBrand"><div className="brand light">Job<span>Hub</span></div><h1>One platform.<br/>Six professional experiences.</h1><p>Phase 1 demonstrates real backend identity, JWT authentication, tenant context and role-based access.</p><div className="callout">Demo password: <b>parrot421$</b></div></section><section className="loginForm"><div className="head"><div><h2>Sign in</h2><p>Select a persona to preview the access model.</p></div></div><div className="roleGrid">{Object.entries(roles).map(([k,v])=><button key={k} className={role===k?'selected':''} onClick={()=>setRole(k)}><b>{v[0]}</b><small>{v[1]}</small></button>)}</div><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="btn primary full" disabled={busy}>{busy?'Signing in…':'Sign in to workspace'}</button></form><button className="textBtn" onClick={()=>router.push('/')}>← Back to JobHub</button></section></div></main>}
